name: Build
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: 3.8
        #- os: ubuntu-latest
        #  python: 3.9
        #- os: ubuntu-latest
        #  python: '3.10'
    runs-on: ${{ matrix.os }}
    name: Python ${{ matrix.python }}
    steps:
    - uses: actions/checkout@v2
    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: apt update
      run:
        sudo apt-get update
    - name: apt dependencies
      run:
        sudo apt-get install
          libgtk-3-dev
          gettext
          libjpeg-dev
          libpng-dev
          libtiff-dev
          libnotify-dev
          libsm-dev
    - name: download dependencies
      run: |
        pip install -U pip
        pip install -U six wheel setuptools
    - name: download source
      run:
        pip download wxPython
    - run:
        ls -l
    - name: run build
      run:
        pip wheel -v *.tar.gz
